import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
const title = "OSLO";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    // router.push("/program");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by a magician" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>
        <hr />
                
      </main>

      <footer className={styles.footer}>©hansmaast</footer>
    </div>
  );
}
