name: Trigger Site Rebuild and Scraping on schedule

on:
  schedule:
    - cron: '07 11 * * */1'
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    name: Trigger scrape and build
    runs-on: ubuntu-latest
    steps:
      - name: Post deploy hook
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}      


