name: Trigger Site Rebuild and Scraping on schedule

on:
  schedule:
    - cron: '07 11 * * */1'
  workflow_dispatch:
  
jobs:
  build:
    name: Trigger Build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy hook
        run: echo "Hello, world!"      


