name: Deploy program

on:
  schedule:
  - cron: "27 14 * * */3"
  workflow_dispatch:
jobs:
  generate-program:
    runs-on: macos-latest
    steps:
      - name: Deploy
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}      
      