name: Deploy program

on:
  schedule:
  - cron: "07 11 * * */1"
  workflow_dispatch:
  
jobs:
  generate-program:
    runs-on: macos-latest
    steps:
      - name: Deploy
        run: curl -X POST ${{ secrets.DEPLOY_HOOK }}      
      
