name: deploy-daily
on:
  schedule:
    - cron: '0 1 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call webhook for triggering deployment
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_5UmQiSZEy8cwXEmTEiAjqZxAQvAq/6lrHbzz3X4
